#!/usr/bin/env Rscript
library(Signac)
library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(future)
set.seed(42)
options(future.globals.maxSize = 15 * 1024^3)
plan("multicore", workers = 8)
OUT_DIR  <- "/data/ebaird/scRNAseq/20260522.nanoCT/R_analysis_peaks/output"
FIG_DIR  <- file.path(OUT_DIR, "figures_multires")
dir.create(FIG_DIR, showWarnings = FALSE, recursive = TRUE)
message("=== Loading existing object ===")
combined <- readRDS(file.path(OUT_DIR, "combined_peak_analysis.rds"))
message("  Cells: ", ncol(combined))
resolutions <- c(0.5, 0.8, 1.0, 1.2, 1.5, 2.0)
results <- data.frame(resolution=numeric(), n_clusters=numeric(), largest_cluster_pct=numeric(), smallest_cluster_size=numeric())
for (res in resolutions) {
  message("  Resolution: ", res)
  combined <- FindClusters(combined, graph.name = "joint_snn", resolution = res, algorithm = 1, verbose = FALSE)
  n_clust <- length(unique(combined$seurat_clusters))
  clust_sizes <- table(combined$seurat_clusters)
  message("    Clusters: ", n_clust, " sizes: ", paste(clust_sizes, collapse=", "))
  results <- rbind(results, data.frame(resolution=res, n_clusters=n_clust, largest_cluster_pct=max(clust_sizes)/sum(clust_sizes)*100, smallest_cluster_size=min(clust_sizes)))
  col_name <- paste0("res_", gsub("\\.", "p", res))
  combined[[col_name]] <- combined$seurat_clusters
  p <- DimPlot(combined, reduction = "umap_joint", group.by = col_name, label = TRUE, pt.size = 0.3) + ggtitle(paste0("Resolution = ", res, " (", n_clust, " clusters)")) + NoLegend()
  ggsave(file.path(FIG_DIR, paste0("umap_res", gsub("\\.","p",res), ".png")), p, width = 8, height = 7)
  saveRDS(combined, file.path(OUT_DIR, paste0("combined_peak_analysis_res", gsub("\\.","p",res), ".rds")))
}
saveRDS(combined, file.path(OUT_DIR, "combined_peak_analysis_all_res.rds"))
write.csv(results, file.path(OUT_DIR, "resolution_summary.csv"), row.names = FALSE)
message("\n=== Resolution Summary ===")
print(results)
p_summary <- ggplot(results, aes(x = resolution, y = n_clusters)) + geom_line(color = "steelblue", linewidth = 1.2) + geom_point(color = "steelblue", size = 3) + geom_text(aes(label = n_clust), vjust = -1, size = 4) + theme_minimal() + labs(title = "Clusters vs Resolution", x = "Resolution", y = "N Clusters")
ggsave(file.path(FIG_DIR, "resolution_summary.png"), p_summary, width = 8, height = 5)
message("=== Done ===")
